# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Safe Water Optimization Tool
description:      'Leveraging routine water quality data to guarantee safe water supply and improve the public health of populations living in precarious situations.'
url:              http://swot.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
gems: 
    [jekyll-paginate, jekyll-gist]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde


theme: jekyll-theme-leap-day